### ISSUE TITLE
Can not get `rsi` alert when it is hot

### ISSUE THREAD

**Issue by Limon-O-O** [CryptoSignal/crypto-signal#302] opened 2018-05-18 03:41 UTC
```
settings:
    update_interval: 5
    market_pairs:
        - ADA/BTC
exchanges:
    binance:
        required:
            enabled: true

    bittrex:
        required:
            enabled: false 

indicators:
  rsi:
    - enabled: true
      alert_enabled: true
      alert_frequency: once
      signal:
        - rsi
      hot: 50
      cold: 70
      candle_period: 4h
      period_count: 15
          
notifiers:
    discord:
        required:
            webhook: https://discordapp.com/api/webhooks
            username: CryptoSignal2
        optional:
            avatar: https://bitcoin.org/img/icons/opengraph.png
            template: "[{{analysis.config.candle_period}} / {{analysis.config.period_count}}] {{exchange}} - {{market}} - {{indicator}} - {{indicator_number}} is {{status}}! ({{values}}){{ '\n' -}}"

```

**Comment by shads2** [comment] 2018-05-18 06:43
I will investigate this further when I find time.

**Comment by ikwtif** [comment] 2018-05-23 19:31
Not sure if this is related, but some additional info. I'll add my config if needed but it's nothing special. When I set up alert_frequency to always for all my alerts, RSI is never added. This is with telegram notifier.

**Comment by ikwtif** [comment] 2018-05-24 17:57
config: https://pastebin.com/ekxrRMdC

I added this to notification.py

```
                                if should_alert:
                                    print('adding', signal)
                                    new_message += message_template.render(
                                        values=values,
                                        exchange=exchange,
                                        market=market,
                                        indicator=indicator,
                                        indicator_number=index,
                                        analysis=analysis,
                                        status=status,
                                        last_status=last_status
                                    )
```

giving me this:

adding momentum
adding obv
adding obv
adding stoch_rsi
adding macd
adding leading_span_b
adding leading_span_b
adding momentum
adding obv
adding obv
adding stoch_rsi
adding stoch_rsi
adding macd
adding leading_span_b
adding leading_span_b


so several are not added

**Comment by ikwtif** [comment] 2018-05-26 21:12
@shads2 @Limon-O-O 

I deleted my previous comments for missing alerts, it was just because of the setup and that the indicators where neither hot nor cold, not sure how I missed that possibility. 

But this made me look at OP's config.

```
      hot: 50
      cold: 70
```

hot is set lower than cold, wich is probably why there's no alerts.

**Comment by shads2** [comment] 2018-05-27 01:32
Yep that would certainly be the root cause of this issue thanks @ikwtif, I am going to close this as in the initial testing I did I was unable to replicate the problem (when using the correct settings).

**Closed by shads2** 2018-05-27 01:32 UTC
Labels: bug
