### ISSUE TITLE
Stoch RSI possibly innacurate

### ISSUE THREAD

**Issue by rhamnett** [CryptoSignal/crypto-signal#210] opened 2018-03-08 23:56 UTC
Hi, I have a 15m window on bitfinex (only one supporting 15m it seems) using 14 candle count. The values seem erratic and do not match in any way BTC/USD stoch RSI on the tradingview chart. Tried various combinations of candle period and count. Often times trading view will be at 60% and crypto signals will be reporting 20ish for example.

**Comment by shads2** [comment] 2018-03-09 02:49
First thing you should do is read this https://github.com/CryptoSignal/crypto-signal#why-does-tradingview-show-me-different-information-than-crypto-signal if you haven't already.

If I had a dollar for every time this question has come up now I could retire rich. Fundamentally the problem is that in order for me to _do_ anything about this I need some one to be able to prove the code is wrong. No matter how many times we investigate it, as far as we are able to ascertain, there is no fault.

**Comment by shads2** [comment] 2018-03-09 02:59
That said, stochastic is quite new to crypto-signal. Right now the value it is using is the K line which has a value of 0 -> 100 and is meant to be similar to RSI. There is also a D line though based on my rudimentary understanding of stochastic that is used to look for trend line crossovers to detect entry and exit points.

**Comment by rhamnett** [comment] 2018-03-09 22:19
Hi, thanks for the reply. Couple of things - I definitely read that documentation - in fact a number of times prior to submitting. Secondly, it's pretty easy to prove whether it's remotely accurate. If you run your own code and set the 15m chart on tradingview and enable Sotchastic RSI looking at BTC/USDT pair you will immediately see how incorrect it is. I am happy to assist in fixing the issue, I was really looking for some confirmation before we move on. Cheers.

**Comment by shads2** [comment] 2018-03-09 22:46
If you are able to find the source of the problem, I will more than happily fix it.

**Comment by rhamnett** [comment] 2018-03-10 04:11
rsi_values = abstract.STOCHRSI(dataframe, period_count, fastk_period=14, slowk_period=3, slowk_matype=0, slowd_period=3, slowd_matype=0).iloc[:, 0]

So....above works fine for 15 minute, definitely needs params tuning!

**Comment by shads2** [comment] 2018-03-10 22:13
So it looks like the solution to fixing stochastic RSI is here https://github.com/mrjbq7/ta-lib/issues/149 (specifically the second post). it looks like the original implementation does not take into account moving average.

Whether this constitutes an actual problem or not I am still uncertain. I think further reading is required to ascertain whether stochastic without a moving average still tells you anything useful. I would rather not jump right to mimicking tradingview for the sake of mimicking tradingview.

**Comment by shads2** [comment] 2018-04-03 10:50
Fix for stoch RSI implemented in https://github.com/CryptoSignal/crypto-signal/pull/245. This does not add an EMA for Fast K... I don't know if that is something that would be expected or not...

**Comment by shads2** [comment] 2018-04-04 09:50
merged

**Closed by shads2** 2018-04-04 09:50 UTC
Labels: bug, question
