### ISSUE TITLE
stoch_rsi 1hour candle_period not working

### ISSUE THREAD

**Issue by decharel** [CryptoSignal/crypto-signal#291] opened 2018-05-14 20:09 UTC
stoch_rsi indicator does not show any results with 1hour candle_period (but works with 1d)

    stoch_rsi:
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - stoch_rsi
          hot: 20
          cold: 80
          candle_period: 1d
          period_count: 21
        - enabled: true
          alert_enabled: true
          alert_frequency: once
          signal:
            - stoch_rsi
          hot: 20
          cold: 80
          candle_period: 1h
          period_count: 50

**Comment by shads2** [comment] 2018-05-14 21:16
I'll look into this later this week.

**Comment by shads2** [comment] 2018-05-16 00:26
The problem here is that the period_count of 50 is too long for the amount of data we are capable of collecting, which means that it's returning an empty data set. 

Right now we are hampered by the fact every exchange behaves differently when you make a request greater than their retention period, which was making data wildly inaccurate for some exchanges.

**Comment by shads2** [comment] 2018-05-16 04:06
I'm going to close this for now. Feel free to re-open if you think it merits further discussion but this is not a bug, just a limitation on what we can achieve right now.

**Closed by shads2** 2018-05-16 04:06 UTC
Labels: bug
