### ISSUE TITLE
Webhook Notification AttributeError

### ISSUE THREAD

**Issue by dwagenleiter** [CryptoSignal/crypto-signal#277] opened 2018-05-04 05:02 UTC
Hey guys,

First of all, incredible job with this project. This takes away a lot of work while trying to do TA!

Unfortunately, while trying to send data / notifications to a webhook for further processing, I am getting the following error:

Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 64, in run
    self.notifier.notify_all(new_result)
  File "/app/notification.py", line 100, in notify_all
    self.notify_webhook(new_analysis)
  File "/app/notification.py", line 196, in notify_webhook
    new_analysis[exchange][market][indicator_type][indicator][index] = analysis['result'].to_dict(orient='records')[-1]
AttributeError: 'dict' object has no attribute 'to_dict'

It is setup according to the documentation as:

NOTIFIERS_WEBHOOK_REQUIRED_URL=http://xxx/webhook.php

Any ideas what could cause this?

Best,
David

**Comment by shads2** [comment] 2018-05-04 09:51
Sounds like a bug, are you able to provide what config options you are using so I can try to replicate it?

**Comment by dwagenleiter** [comment] 2018-05-04 11:31
I am really just using the standard configuration described in the documentation, I didn't really get to that part yet as I wanted to write my logic first and test around.

SETTINGS_UPDATE_INTERVAL=300
SETTINGS_OUTPUT_MODE=csv

SETTINGS_MARKET_PAIRS=ETH/BTC,BTC/USDT

NOTIFIERS_WEBHOOK_REQUIRED_URL=http://xxx/webhook.php

EXCHANGES_BITTREX_REQUIRED_ENABLED=true
INDICATOR_RSI_NUM_INDICATORS=2
INDICATOR_RSI_0_CANDLE_PERIOD=1d
INDICATOR_RSI_0_PERIOD_COUNT=14
INDICATOR_RSI_1_CANDLE_PERIOD=1h
INDICATOR_RSI_1_PERIOD_COUNT=14
INDICATOR_SMA_0_PERIOD_COUNT=9
INDICATOR_SMA_0_CANDLE_PERIOD=1h

**Comment by dwagenleiter** [comment] 2018-05-04 11:38
Interestingly enough, putting NOTIFIERS_WEBHOOK_REQUIRED_URL=http://xxx/webhook.php to the end of the file fixed the issue.

**Comment by shads2** [comment] 2018-05-04 11:46
That is quite weird... the config file is read in as environment variables so there really shouldn't be any reason for the order to matter... perhaps the issue is just inconsistent? But I will test both in either case and see if I can replicate :)

**Comment by dwagenleiter** [comment] 2018-05-04 11:53
My bad, I temporarily changed SETTINGS_OUTPUT_MODE to CSV and that configuration didn't throw the error (my webhook did not get any data though).

I have changed it back to JSON now and I am getting the error again, each time.

**Comment by shads2** [comment] 2018-05-04 11:56
Excellent, well I'll likely have it fixed within a week.

**Comment by dwagenleiter** [comment] 2018-05-04 12:04
Awesome, thanks!

**Comment by shads2** [comment] 2018-05-05 23:44
Fixed in https://github.com/CryptoSignal/crypto-signal/pull/280

**Comment by shads2** [comment] 2018-05-06 21:10
merged

**Closed by shads2** 2018-05-06 21:10 UTC
Labels: bug
