### ISSUE TITLE
script error still in #264

### ISSUE THREAD

**Issue by rottenronin1** [CryptoSignal/crypto-signal#269] opened 2018-04-28 20:18 UTC
hello, i ran the script with all coins/btc in bittrex and still getting this message:

Traceback (most recent call last):
  File "app.py", line 45, in <module>
    main()
  File "app.py", line 39, in main
    behaviour.run(settings['market_pairs'], settings['output_mode'])
  File "/app/behaviour.py", line 64, in run
    self.notifier.notify_all(new_result)
  File "/app/notification.py", line 98, in notify_all
    self.notify_telegram(new_analysis)
  File "/app/notification.py", line 176, in notify_telegram
    self.notifier_config['telegram']['optional']['template']
  File "/app/notification.py", line 240, in _message_templater
    latest_result = analysis['result'].iloc[-1]
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1373, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1830, in _getitem_axis
    self._is_valid_integer(key, axis)
  File "/usr/local/lib/python3.6/site-packages/pandas/core/indexing.py", line 1713, in _is_valid_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

thank you!

**Comment by shads2** [comment] 2018-04-28 21:58
Huh, that is an interesting place to be encountering that error... I would have expected for it to bomb out earlier in execution if that condition occurred. I will look into it when I get a chance.

**Comment by rhamnett** [comment] 2018-04-28 22:09
Looks like a problem with his configuration settings.

**Comment by shads2** [comment] 2018-04-28 22:12
Could be, I think the problem is that it's somehow getting to the notifier stage but there's nothing left on the result stack `analysis['result'].iloc[-1]`. Either way @rottenronin1 can you paste your config?

**Comment by rottenronin1** [comment] 2018-04-28 22:30
thank you sir!

NOTIFIERS_TELEGRAM_REQUIRED_TOKEN=xxxx
#default: None
#necessity: required for Telegram
#description: Your telegram bot token you can generate a token by following the instructions here

NOTIFIERS_TELEGRAM_REQUIRED_CHAT_ID=xxx
#default: 
#necessity: required for Telegram
#description: The chat_id to send the message too. The easiest way to get get this id is probably using RawDataBot or Userinfobot.

#NOTIFIERS_TELEGRAM_OPTIONAL_TEMPLATE
#default: {{exchange}}-{{market}}-{{analyzer}}-{{analyzer_number}} is {{status}}!{{ '\n' -}}
#necessity: optional
#description: See the notifier templating section.

#setting RSI
INDICATOR_RSI_0_CANDLE_PERIOD=5m
INDICATOR_RSI_0_PERIOD_COUNT=14

SETTINGS_MARKET_PAIRS=2GIVE/BTC,ABY/BTC,ADA/BTC,ADT/BTC,ADX/BTC,AEON/BTC,AMP/BTC,ANT/BTC,ARDR/BTC,ARK/BTC,AUR/BTC,BAT/BTC,BAY/BTC,BCC/BTC,BCPT/BTC,BCY/BTC,BITB/BTC,BLITZ/BTC,BLK/BTC,BLOCK/BTC,BNT/BTC,BRK/BTC,BRX/BTC,BSD/BTC,BTG/BTC,BURST/BTC,BYC/BTC,CANN/BTC,CFI/BTC,CLAM/BTC,CLOAK/BTC,COVAL/BTC,CRB/BTC,CRW/BTC,CURE/BTC,CVC/BTC,DASH/BTC,DCR/BTC,DCT/BTC,DGB/BTC,DMD/BTC,DMT/BTC,DNT/BTC,DOGE/BTC,DOPE/BTC,DTB/BTC,DYN/BTC,EBST/BTC,EDGBTC,EFL/BTC,EGC/BTC,EMC/BTC,EMC2/BTC,ENG/BTC,ENRG/BTC,ERC/BTC,ETC/BTC,ETH/BTC,EXCL/BTC,EXP/BTC,FCT/BTC,FLDC/BTC,FLO/BTC,FTC/BTC,GAM/BTC,GAME/BTC,GBG/BTC,GBYTE/BTC,GEO/BTC,GLD/BTC,GNO/BTC,GNT/BTC,GOLOS/BTC,GRC/BTC,GRS/BTC,GUP/BTC,HMQ/BTC,IGNIS/BTC,INCNT/BTC,IOC/BTC,ION/BTC,IOP/BTC,KMD/BTC,KORE/BTC,LBC/BTC,LGD/BTC,LMC/BTC,LRC/BTC,LSK/BTC,LTC/BTC,LUN/BTC,MANA/BTC,MCO/BTC,MEME/BTC,MER/BTC,MLN/BTC,MONA/BTC,MUE/BTC,MUSIC/BTC,NAV/BTC,NBT/BTC,NEO/BTC,NEOS/BTC,NLG/BTC,NMR/BTC,NXC/BTC,NXS/BTC,NXT/BTC,OK/BTC,OMG/BTC,OMNI/BTC,PART/BTC,PAY/BTC,PINK/BTC,PIVX/BTC,POLY/BTC,POT/BTC,POWR/BTC,PPC/BTC,PRO/BTC,PTC/BTC,PTOY/BTC,QRL/BTC,QTUM/BTC,RADS/BTC,RBY/BTC,RCN/BTC,RDD/BTC,REP/BTC,RLC/BTC,RVR/BTC,SALT/BTC,SBD/BTC,SC/BTC,SEQ/BTC,SHIFT/BTC,SIB/BTC,SLR/BTC,SLS/BTC,SNRG/BTC,SNT/BTC,SPHR/BTC,SPR/BTC,SRN/BTC,STEEM/BTC,STORJ/BTC,STRAT/BTC,SWIFT/BTC,SWT/BTC,SYNX/BTC,SYS/BTC,THC/BTC,TIX/BTC,TKS/BTC,TRST/BTC,TRUST/BTC,TRX/BTC,TUSD/BTC,TX/BTC,UBQ/BTC,UKG/BTC,UNB/BTC,UP/BTC,VEE/BTC,VIA/BTC,VIB/BTC,VRC/BTC,VRM/BTC,VTC/BTC,VTR/BTC,WAVES/BTC,WAX/BTC,WINGS/BTC,XCP/BTC,XDN/BTC,XEL/BTC,XEM/BTC,XLM/BTC,XMG/BTC,XMR/BTC,XMY/BTC,XRP/BTC,XST/BTC,XVC/BTC,XWC/BTC,XZC/BTC,ZCL/BTC,ZEC/BTC,ZEN/BTC,ZRX/BTC

SETTINGS_UPDATE_INTERVAL=300
EXCHANGES_BITTREX_REQUIRED_ENABLED=true

**Comment by rottenronin1** [comment] 2018-04-28 22:31
i forgot to add that it would go through all the coin pairs then spit out that error/message in the end. thanks again!

**Comment by tomthedude** [comment] 2018-04-29 00:00
yeah here too, same issue with telegram, going through all coins and them crash. :(

**Comment by tomthedude** [comment] 2018-04-29 01:40
hi it is possible telegram crash, i notice i did not get any kind of message for couple of hours, here is a some stats.. a lot of problems reported in the last 3-4 hours,.... may be not app related
http://downdetector.com/status/telegram

**Comment by shads2** [comment] 2018-04-29 10:46
The issue as created by @rottenronin1 is definitely a bug, as it so happens though... I may have inadvertantly fixed it as part of https://github.com/CryptoSignal/crypto-signal/pull/271. I'll have to perform some further testing tomorrow if I get a chance.

**Comment by rottenronin1** [comment] 2018-04-29 22:26
ohhh cool! cant wait to try #271. thanks!

**Comment by shads2** [comment] 2018-04-30 10:26
merged, I think the issue is resolved.

**Closed by shads2** 2018-04-30 10:26 UTC
Labels: bug
