### ISSUE TITLE
RSI not getting enabled in Notifier

### ISSUE THREAD

**Issue by rajnet70** [CryptoSignal/crypto-signal#234] opened 2018-03-24 10:23 UTC
Terminal is fine but not getting alerts in discord while getting the rest of them, following are my settings fro RSI:

BEHAVIOUR_RSI_ENABLED=true 
BEHAVIOUR_RSI_ALERT_ENABLED=true

**Comment by shads2** [comment] 2018-03-24 10:58
This is a duplicate of the issue you already opened https://github.com/CryptoSignal/crypto-signal/issues/226 where we are still waiting for further information.

**Closed by shads2** 2018-03-24 10:58 UTC
Labels: duplicate
